### ISSUE TITLE
LFS  - This repository is over its data quota.

### ISSUE THREAD

**Issue by gshipman** [lanl/spatter#11]
Users of the Spatter repo are getting an error when cloning: 

```
git clone [https://github.com/lanl/spatter.git](https://urldefense.com/v3/__https:/github.com/lanl/spatter.git__;!!Bt8fGhp8LhKGRg!G-Kduotmzacolbg7_51mmoB1Lac1b4uKoJ_itbUvl0X5yk_KDV4M24ekwT3GmkxpWU1PIAuGtVxbQrlw$)
Cloning into 'spatter'...
remote: Enumerating objects: 410, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 410 (delta 1), reused 1 (delta 1), pack-reused 364
Receiving objects: 100% (410/410), 64.06 KiB | 1.94 MiB/s, done.
Resolving deltas: 100% (247/247), done.
Downloading patterns/flag/static_2d/001.fp.json.tar.gz (296 KB)
Error downloading object: patterns/flag/static_2d/001.fp.json.tar.gz (5b0f120): Smudge error: Error downloading patterns/flag/static_2d/001.fp.json.tar.gz (5b0f120e39a5e173e01e80cf00bba2db9c945a5cc65ec132934210199378c0dc): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

@junghans As the owner of the LANL organization I think you may be able to adjust the LFS archive options. 
See: https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh
I and @JDTruj2018  don't see the option to Check on the checkbox of Include Git LFS objects in archives.
Can you take a look as owner and see if you can make this change? 
Thanks

**Comment by JDTruj2018** [comment]
If that doesn't work, we may just be over the data limit for LFS. I'm not sure why we would suddenly be over the limit since this had worked for a while and we haven't added any new data to LFS for this repo in quite some time. My best guess is another repo in the lanl org is also using LFS and may have added additional data that pushed us over the 1 GiB limit.

Viewing our (lanl) usage:
https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/viewing-your-git-large-file-storage-usage

Upgrading the LFS storage quota for the org:
https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/upgrading-git-large-file-storage

**Comment by junghans** [comment]
Yup, we are out of LFS quota, other project have the same issue.

**Comment by JDTruj2018** [comment]
Would it be possible to purchase a higher quota or should we start brainstorming an alternative solution?

**Comment by JDTruj2018** [comment]
See the current work-around in the main branch and referenced here: https://github.com/lanl/benchmarks/pull/108

**Comment by junghans** [comment]
This is solved.
